# Generated by Django 3.0.2 on 2020-05-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200220_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_link',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_status',
        ),
        migrations.AddField(
            model_name='course',
            name='course_detail',
            field=models.TextField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_img',
            field=models.URLField(default='defualt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_detail',
            field=models.TextField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_img',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_title', models.CharField(max_length=300)),
                ('subtopic_status', models.BooleanField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Topic')),
            ],
        ),
    ]
