# Generated by Django 3.0.2 on 2020-05-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_userscore_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_detail',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
