# Generated by Django 3.0.2 on 2020-05-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_exam_exam_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_detail',
            field=models.TextField(default='thsk cisf nka[powm wfmow mkla; ckmdcosma.,emlfandonmalsefm;xlz;nkjshjowjlrfmls', max_length=300),
            preserve_default=False,
        ),
    ]
