# Generated by Django 3.0.2 on 2020-05-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20200529_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_imglink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='svg_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
